### ISSUE TITLE
"TypeError: telegramBot._request is not a function" when editMessageMedia after callback

### ISSUE THREAD

**Issue by halamov** [windkh/node-red-contrib-telegrambot#277]
Last worked in 14.3.0 version
After upgrading to a version higher than 14.3.0, I get the following error "TypeError: telegramBot._request is not a function" when trying to send an edited message from callback.
NodeJS 14 and 16 same error
NodeRED 2.2.3

**Comment by windkh** [comment]
@halamov Thanks for reporting... that is a type introduced accidentally
