### ISSUE TITLE
Problem to upgrade to v17.0.4

### ISSUE THREAD

**Issue by labodj** [windkh/node-red-contrib-telegrambot#423]
I just experienced problems when updating from v17.0.3 to v17.0.4, node-red cannot start since it can't find telegrambot modules
Here is the log

```txt
node-red  | Welcome to Node-RED
node-red  | ===================
node-red  | 
node-red  | 11 Jan 13:02:28 - [info] Node-RED version: v4.1.3
node-red  | 11 Jan 13:02:28 - [info] Node.js  version: v22.21.1
node-red  | 11 Jan 13:02:28 - [info] Linux 6.18.4-arch1-1 x64 LE
node-red  | 11 Jan 13:02:29 - [info] Loading palette nodes
node-red  | 11 Jan 13:02:29 - [info] node-red-contrib-telegrambot version: v17.0.4
node-red  | 11 Jan 13:02:29 - [warn] ------------------------------------------------------
node-red  | 11 Jan 13:02:29 - [warn] [node-red-contrib-telegrambot/telegrambot] Error: Cannot find module '../lib/converter.js<'
node-red  | Require stack:
node-red  | - /data/node_modules/node-red-contrib-telegrambot/telegrambot/nodes/in-node.js
node-red  | - /data/node_modules/node-red-contrib-telegrambot/telegrambot/99-telegrambot.js
node-red  | - /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
node-red  | - /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
node-red  | - /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
node-red  | - /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
node-red  | - /usr/src/node-red/node_modules/node-red/lib/red.js
node-red  | - /usr/src/node-red/node_modules/node-red/red.js
node-red  | 11 Jan 13:02:29 - [warn] ------------------------------------------------------
...
node-red  | 11 Jan 13:02:29 - [info] Waiting for missing types to be registered:
node-red  | 11 Jan 13:02:29 - [info]  - telegram bot
node-red  | 11 Jan 13:02:29 - [info]  - telegram sender
node-red  | 11 Jan 13:02:29 - [info]  - telegram command
```

Switching back manually to v17.0.3 solves the problem

`npm install node-red-contrib-telegrambot@17.0.3`
