### ISSUE TITLE
node-red nodes fail to start: TypeError: Promise.config is not a function (line:11)

### ISSUE THREAD

**Issue by mariusbach** [windkh/node-red-contrib-telegrambot#145]
Hi there,

since today, my node-red nodes fail to start and I have to delete all telegrambot nodes entirely to be able to deloy the flows. The error message is:

`
TypeError: Promise.config is not a function (line:11)`

My versions:
[info] Node-RED version: v1.2.6
[info] Node.js  version: v14.15.1
[info] Linux 5.4.72-v7l+ arm LE

I thought I report it here, but I'm not into the code of telegrambot to determine what exactly has gone wrong. I'm using node-red on a raspberry pi 4. Let me know if you need more details, please. I also installed 8.9.2 but had the same issue, so I went back to 8.9.3. Perhaps I find time to test previous releases, because it was working nicely until today.

Thanks for looking into this.

**Comment by windkh** [comment]
Hm that comes from bluebird... but what nodejs version do you have? (node --version)

**Comment by mariusbach** [comment]
Thanks for the quick reply. I just added the versions to the issue:

[info] Node-RED version: v1.2.6
[info] Node.js  version: v14.15.1
[info] Linux 5.4.72-v7l+ arm LE

**Comment by windkh** [comment]
hm that is really strange.... thanks for reporting.

**Comment by mariusbach** [comment]
If it helps, it also occurs with 8.9.1, so I guess it must be a dependency which causes the issue.

<img width="563" alt="error with 8.9.1" src="https://user-images.githubusercontent.com/58884413/100716248-ba728b00-33b8-11eb-8405-6ae7854b1376.png">

**Comment by mariusbach** [comment]
One more data point, when updating to 8.9.3, I see this:

```
2020-12-01T08:37:22.107Z Install : node-red-contrib-telegrambot 8.9.3

2020-12-01T08:37:22.290Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-telegrambot@8.9.3
2020-12-01T08:37:28.770Z [err] npm
2020-12-01T08:37:28.770Z [err]  WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
2020-12-01T08:37:33.109Z [err] npm
2020-12-01T08:37:33.109Z [err]  WARN node-red-project@0.0.1 No repository field.
2020-12-01T08:37:33.129Z [err] npm 
2020-12-01T08:37:33.130Z [err] WARN node-red-project@0.0.1 No license field.
2020-12-01T08:37:33.130Z [err] 
2020-12-01T08:37:33.132Z [out] + node-red-contrib-telegrambot@8.9.3
2020-12-01T08:37:33.132Z [out] updated 1 package in 9.504s
2020-12-01T08:37:33.161Z rc=0
```

**Comment by windkh** [comment]
Yes I know: the request package was marked as deprecated but there is no package that could replace the existing implementation.
I guess I will have to add a dependency to bluebird in package json.

**Comment by mariusbach** [comment]
Thanks a lot for the hint. I just installed bluebird via `npm install bluebird` and it all works again!

**Comment by DavidBadura** [comment]
Hello, I just wanted to tell you that I have the exact same problem. Btw. thank you for your amazing work :)

**Comment by windkh** [comment]
> Thanks a lot for the hint. I just installed bluebird via `npm install bluebird` and it all works again!

Ok thanks

**Comment by Edupotamo** [comment]
Hello:

same problem here even after install bluebird from npm and reinstall the node from rpm:

>  npm install node-red-contrib-telegrambot --save
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No license field.

my node red version:

>  Dec 19:55:42 - [info] Node-RED version: v1.2.6
1 Dec 19:55:42 - [info] Node.js  version: v10.23.0
1 Dec 19:55:42 - [info] Linux 4.19.66-v7+ arm LE
1 Dec 19:55:43 - [info] Loading palette nodes
1 Dec 19:55:49 - [info] Dashboard version 2.24.2 started at /ui
1 Dec 19:55:51 - [warn] ------------------------------------------------------
1 Dec 19:55:51 - [warn] [node-red-contrib-telegrambot/telegrambot] TypeError: Promise.config is not a function (line:11)
1 Dec 19:55:51 - [warn] ------------------------------------------------------
1 Dec 19:55:51 - [info] Settings file  : /home/pi/.node-red/settings.js
1 Dec 19:55:51 - [info] Context store  : 'default' [module=memory]
1 Dec 19:55:51 - [info] User directory : /home/pi/.node-red
1 Dec 19:55:51 - [warn] Projects disabled : editorTheme.projects.enabled=false
1 Dec 19:55:51 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
1 Dec 19:55:51 - [info] Server now running at http://127.0.0.1:1880/
1 Dec 19:55:51 - [info] Waiting for missing types to be registered:
1 Dec 19:55:51 - [info]  - telegram bot
1 Dec 19:55:51 - [info]  - telegram receiver
1 Dec 19:55:51 - [info]  - telegram sender

Maybe some step is missing..

**Comment by windkh** [comment]
can you please retry with version 8.9.4?
I added the bluebird dependency to package.json.

**Comment by Edupotamo** [comment]
after telegram node install:

> npm install node-red-contrib-telegrambot --save
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No license field.

+ node-red-contrib-telegrambot@8.9.4
updated 1 package and audited 97 packages in 16.259s
found 0 vulnerabilities

the result on the console after restart node red is:

> ===================
1 Dec 20:58:01 - [info] Node-RED version: v1.2.6
1 Dec 20:58:01 - [info] Node.js  version: v10.23.0
1 Dec 20:58:01 - [info] Linux 4.19.66-v7+ arm LE
1 Dec 20:58:02 - [info] Loading palette nodes
1 Dec 20:58:07 - [info] Dashboard version 2.24.2 started at /ui
1 Dec 20:58:10 - [warn] ------------------------------------------------------
1 Dec 20:58:10 - [warn] [node-red-contrib-telegrambot/telegrambot] TypeError: Promise.config is not a function (line:11)
1 Dec 20:58:10 - [warn] ------------------------------------------------------
1 Dec 20:58:10 - [info] Settings file  : /home/pi/.node-red/settings.js
1 Dec 20:58:10 - [info] Context store  : 'default' [module=memory]
1 Dec 20:58:10 - [info] User directory : /home/pi/.node-red
1 Dec 20:58:10 - [warn] Projects disabled : editorTheme.projects.enabled=false
1 Dec 20:58:10 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
1 Dec 20:58:10 - [info] Server now running at http://127.0.0.1:1880/
1 Dec 20:58:10 - [info] Waiting for missing types to be registered:
1 Dec 20:58:10 - [info]  - telegram bot
1 Dec 20:58:10 - [info]  - telegram receiver
1 Dec 20:58:10 - [info]  - telegram sender

Also here the config.json file:

> {
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "node-red-contrib-telegrambot": "^8.9.4"
  },
  "devDependencies": {
    "bluebird": "^3.7.2"
  }
}

but as something wrong status the npm installation it is not applied to the pallate:

![image](https://user-images.githubusercontent.com/40772337/100791846-0f92b900-341a-11eb-9e98-d14b07155014.png)

**Comment by windkh** [comment]
You are using 8.9.3 not 8.9.4. Please try again

**Comment by DavidBadura** [comment]
I just tested it. Version 8.9.4 works again. Thank you so much!

**Comment by DavidBadura** [comment]
Btw. node-red could not upgrade it directly (even if it was 8.9.4 installing). I had to restart node-red. But that is very likely not related to this package.

**Comment by Edupotamo** [comment]
Thank you Team, issue solved when the comand
` npm install node-red-contrib-telegrambot --save`
was executed on a terminal inside the pi/.node-red folder, I was executing at pi/
now running 8.9.4 properly

Thank you very much for support.
